#!/usr/bin/env bash
#
# Assemble the shen-cl `kernel/` tree for Mark Tarver's S42.0
# distribution (uploaded 2026-08-25 to shenlanguage.org).
#
# WHY THIS EXISTS
# ---------------
# shen-cl's supported `make fetch` assembles this hybrid kernel. The raw
# community `shen-sources` release (github.com/Shen-Language/shen-sources) has
# a klambda/ lib/ tests/ extensions/ sources/ layout. Tarver's S42.0 is a
# restructured distribution:
# it ships KLambda/ (uppercase), Primitives/, Lib/, backend.lsp + install.lsp
# for a direct SBCL install, and it DROPS compiler.kl, dict.kl, init.kl,
# stlib.kl and every extension-*.kl. It is not a github release, so `make
# fetch` cannot consume it.
#
# shen-cl's build harness (src/compiler.shen generates compiler.kl; boot.lsp
# assembles the image; the launcher CLI yggdrasil depends on lives in
# extension-launcher.kl) needs those dropped pieces. So this script builds a
# HYBRID kernel:
#   * the 14 KLambda files shared by both lineages  -> taken from Tarver's refresh
#   * extension-features / -expand-dynamic / -launcher, stlib -> kept from the
#     community ShenOSKernel-41.2 release (Tarver dropped them; shen-cl needs
#     them, and its src/overwrite.lsp shims the few community-init functions
#     they reference: shen.set-lambda-form-entry, shen.toplevel-display-exception)
#   * tests/ lib/ extensions/  -> community release (language-agnostic Shen)
#   * dict.kl / init.kl / compiler.kl are intentionally NOT included:
#       - dict.kl : shen-cl provides native hash-table dicts in overwrite.lsp
#       - init.kl : the refresh folds shen.initialise's work into declarations.kl
#                   load-time forms; overwrite.lsp shims a no-op shen.initialise
#       - compiler.kl : generated by `make precompile` from src/compiler.shen
#
# PROVENANCE (see docs/KERNEL-PROVENANCE-tarver-s42.0.md)
#   Canonical: pyrex41/shen-upstream mirror, planned tag
#     s42.0-pristine-20260825 -- pass its checkout as $1 to build from the
#     pinned copy.
#   Secondary: https://www.shenlanguage.org/Download/S42.zip
#     Last-Modified 2026-08-25 (hash pins this revision)
#     sha256 30abdc7e5a1e27b7a20109c1ed141e4712885e31f24d9710d16415fbbd4dfb23
#   Community grafts:     github.com/Shen-Language/shen-sources tag shen-41.2
#
# USAGE
#   scripts/assemble-tarver-kernel.sh [TARVER_S41_DIR] [COMMUNITY_KERNEL_DIR]
# If arguments are omitted the script downloads both into a scratch dir.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARVER_SHA256="30abdc7e5a1e27b7a20109c1ed141e4712885e31f24d9710d16415fbbd4dfb23"
TARVER_URL="https://www.shenlanguage.org/Download/S42.zip"
COMMUNITY_URL="https://github.com/Shen-Language/shen-sources/releases/download/shen-41.2/ShenOSKernel-41.2.tar.gz"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

TARVER_DIR="${1:-}"
COMMUNITY_DIR="${2:-}"

if [ -z "$TARVER_DIR" ]; then
  echo "Downloading Tarver S42.0 release..."
  curl -fsSL "$TARVER_URL" -o "$WORK/S42.zip"
  GOT="$(shasum -a 256 "$WORK/S42.zip" | awk '{print $1}')"
  if [ "$GOT" != "$TARVER_SHA256" ]; then
    echo "WARNING: S42.zip sha256 mismatch."
    echo "  expected $TARVER_SHA256"
    echo "  got      $GOT"
    echo "Tarver re-uploads this file in place; verify the change is intended."
  fi
  ( cd "$WORK" && unzip -q S42.zip )
  TARVER_DIR="$WORK/S42"
fi

if [ -z "$COMMUNITY_DIR" ]; then
  echo "Downloading community ShenOSKernel-41.2 (for grafts)..."
  curl -fsSL "$COMMUNITY_URL" -o "$WORK/community.tar.gz"
  ( cd "$WORK" && tar zxf community.tar.gz )
  COMMUNITY_DIR="$WORK/ShenOSKernel-41.2"
fi

echo "Tarver dir:    $TARVER_DIR"
echo "Community dir: $COMMUNITY_DIR"

KERNEL="$REPO_ROOT/kernel"
rm -rf "$KERNEL"
mkdir -p "$KERNEL/klambda"

# 14 KLambda files shared by both lineages: take Tarver's refreshed versions.
for f in core declarations load macros prolog reader sequent sys t-star \
         toplevel track types writer yacc; do
  cp "$TARVER_DIR/KLambda/$f.kl" "$KERNEL/klambda/$f.kl"
done

# Community extensions Tarver dropped but shen-cl still needs. NOTE: stlib.kl
# is NO LONGER grafted -- the standard library is now installed from Tarver's
# canonical StLib SOURCES at build time (see below and boot.lsp). The launcher
# is a deliberate, documented community-sourced extension: Tarver's
# distribution ships no non-interactive CLI, and yggdrasil stage-1 depends on
# `eval -l file -e expr`.
for f in extension-features extension-expand-dynamic extension-launcher; do
  cp "$COMMUNITY_DIR/klambda/$f.kl" "$KERNEL/klambda/$f.kl"
done

# stlib.kl: ECL ONLY. SBCL and CLISP install the standard library from Tarver's
# canonical StLib sources baked into the saved image (see below + boot.lsp).
# ECL's c:build-program cannot bake image state, and loading the sources at
# startup costs ~105s (ECL C-compiles each definition on load), so ECL alone
# keeps the precompiled community stlib.kl graft. Retiring it needs a
# StLib->.lsp packager (fleet follow-up). This is the one stdlib divergence
# across implementations.
cp "$COMMUNITY_DIR/klambda/stlib.kl" "$KERNEL/klambda/stlib.kl"

# Language-agnostic Shen trees from the community release (tests + extensions).
cp -R "$COMMUNITY_DIR/tests"      "$KERNEL/tests"
cp -R "$COMMUNITY_DIR/extensions" "$KERNEL/extensions"

# Standard library: Tarver's canonical StLib sources (typechecked + loaded into
# the image at build time by boot.lsp, exactly as Tarver's own install.lsp
# does). Canonical source: pyrex41/shen-upstream tag s41.2-pristine-20260711,
# Lib/StLib. Replaces the former community stlib.kl graft.
mkdir -p "$KERNEL/lib"
cp -R "$TARVER_DIR/Lib/StLib" "$KERNEL/lib/StLib"

echo "Assembled kernel at $KERNEL (SBCL/CLISP: StLib from Tarver source; ECL: stlib.kl graft)"
echo "Next: make precompile SHEN=<working-shen> && make build-sbcl"
