#!/usr/bin/env bash
#
# Assemble the shen-cl `kernel/` tree for Mark Tarver's refreshed S41.2
# distribution (re-uploaded 2026-07-11 to shenlanguage.org).
#
# WHY THIS EXISTS
# ---------------
# shen-cl normally runs `make fetch`, which downloads a community
# shen-sources release (github.com/Shen-Language/shen-sources) whose layout is
# klambda/ lib/ tests/ extensions/ sources/. Tarver's refreshed S41.2 is a
# DIFFERENT distribution (same "41.2" version number, restructured kernel):
# it ships KLambda/ (uppercase), Primitives/, Lib/, backend.lsp + install.lsp
# for a direct SBCL install, and it DROPS compiler.kl, dict.kl, init.kl,
# stlib.kl and every extension-*.kl. It is not a github release, so `make
# fetch` cannot consume it.
#
# shen-cl's build harness (src/compiler.shen generates compiler.kl; boot.lsp
# assembles the image; the launcher CLI ratatoskr depends on lives in
# extension-launcher.kl) needs those dropped pieces. So this script builds a
# HYBRID kernel:
#   * the 14 KLambda files shared by both lineages  -> taken from Tarver's refresh
#   * extension-features / -expand-dynamic / -launcher, stlib -> kept from the
#     community ShenOSKernel-41.2 release (Tarver dropped them; shen-cl needs
#     them, and its src/overwrite.lsp shims the few community-init functions
#     they reference: shen.set-lambda-form-entry, shen.toplevel-display-exception)
#   * tests/ lib/ extensions/  -> community release (language-agnostic Shen)
#   * dict.kl / init.kl / compiler.kl are intentionally NOT included:
#       - dict.kl : shen-cl provides native hash-table dicts in overwrite.lsp
#       - init.kl : the refresh folds shen.initialise's work into declarations.kl
#                   load-time forms; overwrite.lsp shims a no-op shen.initialise
#       - compiler.kl : generated by `make precompile` from src/compiler.shen
#
# PROVENANCE (see docs/KERNEL-PROVENANCE-tarver-s41.2.md)
#   Canonical: pyrex41/shen-s41.1 mirror, tag s41.2-pristine-20260711 (commit
#     11fc51b) -- pass its checkout as $1 to build from the pinned copy.
#   Secondary: https://www.shenlanguage.org/Download/S41.2.zip
#     Last-Modified 2026-07-11 (re-uploaded in place; hash pins this revision)
#     sha256 51becbfd60fa8c93c3f8ae5b20b948eaa84c4b1d14ad2f5d2a056002a53ee836
#   Community grafts:     github.com/Shen-Language/shen-sources tag shen-41.2
#
# USAGE
#   scripts/assemble-tarver-kernel.sh [TARVER_S41_DIR] [COMMUNITY_KERNEL_DIR]
# If arguments are omitted the script downloads both into a scratch dir.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARVER_SHA256="51becbfd60fa8c93c3f8ae5b20b948eaa84c4b1d14ad2f5d2a056002a53ee836"
TARVER_URL="https://www.shenlanguage.org/Download/S41.2.zip"
COMMUNITY_URL="https://github.com/Shen-Language/shen-sources/releases/download/shen-41.2/ShenOSKernel-41.2.tar.gz"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

TARVER_DIR="${1:-}"
COMMUNITY_DIR="${2:-}"

if [ -z "$TARVER_DIR" ]; then
  echo "Downloading Tarver S41.2 refresh..."
  curl -fsSL "$TARVER_URL" -o "$WORK/S41.2.zip"
  GOT="$(shasum -a 256 "$WORK/S41.2.zip" | awk '{print $1}')"
  if [ "$GOT" != "$TARVER_SHA256" ]; then
    echo "WARNING: S41.2.zip sha256 mismatch."
    echo "  expected $TARVER_SHA256"
    echo "  got      $GOT"
    echo "Tarver re-uploads this file in place; verify the change is intended."
  fi
  ( cd "$WORK" && unzip -q S41.2.zip )
  TARVER_DIR="$WORK/S41"
fi

if [ -z "$COMMUNITY_DIR" ]; then
  echo "Downloading community ShenOSKernel-41.2 (for grafts)..."
  curl -fsSL "$COMMUNITY_URL" -o "$WORK/community.tar.gz"
  ( cd "$WORK" && tar zxf community.tar.gz )
  COMMUNITY_DIR="$WORK/ShenOSKernel-41.2"
fi

echo "Tarver dir:    $TARVER_DIR"
echo "Community dir: $COMMUNITY_DIR"

KERNEL="$REPO_ROOT/kernel"
rm -rf "$KERNEL"
mkdir -p "$KERNEL/klambda"

# 14 KLambda files shared by both lineages: take Tarver's refreshed versions.
for f in core declarations load macros prolog reader sequent sys t-star \
         toplevel track types writer yacc; do
  cp "$TARVER_DIR/KLambda/$f.kl" "$KERNEL/klambda/$f.kl"
done

# Community grafts Tarver dropped but shen-cl still needs.
for f in extension-features extension-expand-dynamic extension-launcher stlib; do
  cp "$COMMUNITY_DIR/klambda/$f.kl" "$KERNEL/klambda/$f.kl"
done

# Language-agnostic Shen trees from the community release.
cp -R "$COMMUNITY_DIR/tests"      "$KERNEL/tests"
cp -R "$COMMUNITY_DIR/lib"        "$KERNEL/lib"
cp -R "$COMMUNITY_DIR/extensions" "$KERNEL/extensions"

echo "Assembled hybrid kernel at $KERNEL"
echo "Next: make precompile SHEN=<working-shen> && make build-sbcl"
